# Generated by Django 5.2.1 on 2025-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_in_stock_alter_catagory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='banner',
            field=models.URLField(),
        ),
    ]
