# Generated by Django 5.2.1 on 2025-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_slider_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='banner',
            field=models.ImageField(upload_to='banners'),
        ),
    ]
