# Generated by Django 5.2.1 on 2025-06-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total',
            new_name='total',
        ),
    ]
