# Generated by Django 5.2.1 on 2025-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_total_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirm order', 'Confirm order'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Recieved', max_length=15),
        ),
    ]
