# Generated by Django 5.2.1 on 2025-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumbnail',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='tittle',
            field=models.CharField(default=True, max_length=250, unique=True),
        ),
    ]
