# Generated by Django 5.2.1 on 2025-06-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_thumbnail_order_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thumbnail',
            field=models.URLField(default=True),
        ),
    ]
