# Generated by Django 5.2.1 on 2025-06-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tittle',
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='order_thumbnails/'),
        ),
    ]
