# Generated by Django 5.2.1 on 2025-06-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_tittle_order_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
